# Generated by Django 3.1.1 on 2020-09-27 23:58

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0002_product_image'),
    ]

    operations = [
        migrations.RenameField(
            model_name='product',
            old_name='degital',
            new_name='digital',
        ),
    ]
